document.addEventListener('DOMContentLoaded',()=>{const{jsPDF:e}=window.jspdf,t=document.getElementById("main-menu-screen"),n=document.getElementById("loading-screen"),o=document.getElementById("storybook-screen"),a=document.getElementById("gallery-screen"),l=document.getElementById("topic-input"),r=document.getElementById("generate-btn"),c=document.getElementById("gallery-btn"),d=document.getElementById("storybook"),i=document.getElementById("prev-page-btn"),s=document.getElementById("next-page-btn"),u=document.getElementById("back-to-main-menu-btn"),m=document.getElementById("save-pdf-btn"),p=document.getElementById("save-to-gallery-btn"),g=document.getElementById("gallery-container"),y=document.getElementById("back-from-gallery-btn"),E=document.getElementById("music-toggle-btn"),h=document.getElementById("bg-music");let b=0,k=0,v=[],f="";let L=!1;const x=e=>{document.querySelectorAll(".screen").forEach(t=>{t.classList.add("hidden")}),e.classList.remove("hidden")},w=()=>{L?(h.pause(),E.classList.remove("playing"),E.textContent="🔇"):(h.play().catch(e=>console.log("音乐播放需要用户交互:",e)),E.classList.add("playing"),E.textContent="🎵"),L=!L};E.addEventListener("click",w);const C=()=>JSON.parse(localStorage.getItem("storybook_gallery")||"{}"),B=(e,t)=>{const n=C();n[e]=t,localStorage.setItem("storybook_gallery",JSON.stringify(n)),alert(`《${e}》已保存到作品库！`)},q=()=>{const e=C();if(g.innerHTML="",0===Object.keys(e).length)return void(g.innerHTML="<p>作品库是空的，快去创作吧！</p>");for(const t in e){const n=e[t],l=document.createElement("div");l.className="gallery-item",l.innerHTML=`
                <img src="${n[0].imageUrl}" alt="${t}">
                <p>${t}</p>
            `,l.addEventListener("click",()=>{S(t,n),x(o)}),g.appendChild(l)}},S=(e,t)=>{f=e,v=t,k=t.length,d.innerHTML="",t.forEach((e,t)=>{const n=document.createElement("div");n.classList.add("page"),n.id=`page-${t}`,n.innerHTML=`
                <div class="page-content">
                    <img src="${e.imageUrl}" alt="绘本图片 ${t+1}">
                    <p class="story-text">${e.text}</p>
                </div>
            `,d.appendChild(n)}),b=0,N(b)},N=e=>{const t=document.querySelectorAll(".page");t.forEach((t,n)=>{t.style.transform=`translateX(${(n-e)*100}%)`}),i.disabled=0===e,s.disabled=e===k-1};r.addEventListener("click",async()=>{const e=l.value.trim();if(!e)return alert("请输入一个主题！");f=e,x(n);try{const t=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:e})});if(!t.ok)throw new Error(`HTTP error! status: ${t.status}`);const a=await t.json();S(e,a.story),x(o)}catch(e){console.error("生成绘本失败:",e),alert("生成绘本失败，请稍后再试。"),x(t)}}),m.addEventListener("click",async()=>{const t=new e({orientation:"landscape",unit:"px",format:[800,600]}),n=document.querySelectorAll(".page-content");for(let e=0;e<n.length;e++){const o=await html2canvas(n[e],{scale:2,useCORS:!0}),a=o.toDataURL("image/png");e>0&&t.addPage(),t.addImage(a,"PNG",0,0,800,600)}t.save(`${f}.pdf`)}),p.addEventListener("click",()=>B(f,v)),c.addEventListener("click",()=>{q(),x(a)}),i.addEventListener("click",()=>{b>0&&N(--b)}),s.addEventListener("click",()=>{b<k-1&&N(++b)});const A=()=>{x(t),l.value=""};u.addEventListener("click",A),y.addEventListener("click",A)});
